### ISSUE TITLE
Can't install laravel-timezone package

### ISSUE THREAD

**Issue by bocanhcam** [jamesmills/laravel-timezone#2]
This is not an issue but i think you should make the docs more clear.

Something like requirement of Laravel version, PHP version.

I use Laravel 5.4 and can't install the package.

**Comment by bscript** [comment]
It works fine on : 
* Laravel 5.7 
* PHP 7.2.x

**Comment by jamesmills** [comment]
Hi!

Thank you for your comments. 

The requirements are listed in the composer file. These will be picked up and displayed in Packagist. 

It’s a relatively new package so I would have thought I would have built and tested this with Laravel above 5.4 however that’s not to say it wouldn’t work. 

I will try find some time to test this with a downgraded version of Laravel and get back to you. It’s probably possible to see from the package files what’s going to be comparisons and what’s not with that version so it shouldn’t take long. Finding the time might be the issue here. 

Thanks, James
