### ISSUE TITLE
localization

### ISSUE THREAD

**Issue by RolandVerner** [jamesmills/laravel-timezone#26]
i use 
            App::setLocale($language);
            Carbon::setLocale($language);
 but with your package it not helps

**Comment by amandiobm** [comment]
I quite don't understand what you meant. Can you be more specific?

**Comment by jamesmills** [comment]
@RolandVerner I'm not sure I am following what your issue is here? Could you provide us with a little more context into what issue you are having and what it is you are trying to achieve?

Just for the record. The Timezone package is meant to help set a timezone for the user and then show them dates/times from your application in that users timezone. It's not got any integration to deal with the "language".

**Comment by thomaswardiii** [comment]
I believe what they're pointing out is that when using `@displayDate` the format is always the same, regardless of the specified locale

**Comment by poseso** [comment]
is it possible to change the locale with this package ?
