### ISSUE TITLE
Crashing Passport

### ISSUE THREAD

**Issue by JLanky** [jamesmills/laravel-timezone#59]
When I installed this package, laravel passport authentication stopped working

**Comment by jamesmills** [comment]
Hi @JLanky 

Are you able to help provide us with any more details about this? Did you manage to find a solution? I'm not that familiar with Passport to know how it would effect using this package.

**Comment by oddvalue** [comment]
@jamesmills the issue here is that the `LaravelTimezoneServiceProvider` event listener attempts to get the session out of the request but since API routes typically don't initiate a session it will throw an exception.

This can be avoided by setting the `timezone.flash` config to 'off' but it would be nice not to have to do that.
